### ISSUE TITLE
ring_examples compilation errors

### ISSUE THREAD

**Issue by karolpivo** [xtao/PF_RING#4]
Hi,

I'd like to  use the pfsend utility but I'm failing to compile it with the  error below.  could you please point me in the right direction? 

Thanks
K

cd examples; make
make[1]: Entering directory '/root/Downloads/PF_RING/userland/examples'
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../../kernel/plugins -I../lib -I../libpcap -Ithird-party  -D HAVE_ZERO -D ENABLE_BPF -D HAVE_LIBNUMA -O2  pfcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a     -lpthread  -lrt   -lnuma -lrt -o pfcount
../libpcap/libpcap.a(grammar.o): In function `pcap_parse':
/root/Downloads/PF_RING/userland/libpcap/y.tab.c:1978: undefined reference to `pcap_lex'
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'pfcount' failed
make[1]: *** [pfcount] Error 1
make[1]: Leaving directory '/root/Downloads/PF_RING/userland/examples'
Makefile:12: recipe for target 'ring_examples' failed
make: *** [ring_examples] Error 2

**Comment by memojoelojo** [comment]
you should ask to the original  github project

**Comment by memojoelojo** [comment]
https://github.com/ntop/PF_RING

**Comment by karolpivo** [comment]
I didn't notice I cloned fork! Thanks
